<?php

$labels = array(
    'name'                  => _x( 'NWS Form submissions', 'Post Type General Name', 'cf7std' ),
    'singular_name'         => _x( 'Form submission', 'Post Type Singular Name', 'cf7std' ),
    'menu_name'             => __( 'NWS Form submissions', 'cf7std' ),
    'name_admin_bar'        => __( 'Form submission', 'cf7std' ),
    'archives'              => __( 'Item Archives', 'cf7std' ),
    'attributes'            => __( 'Item Attributes', 'cf7std' ),
    'parent_item_colon'     => __( 'Parent Item:', 'cf7std' ),
    'all_items'             => __( 'All Items', 'cf7std' ),
    'add_new_item'          => __( 'Add New Item', 'cf7std' ),
    'add_new'               => __( 'Add New', 'cf7std' ),
    'new_item'              => __( 'New Item', 'cf7std' ),
    'edit_item'             => __( 'Edit Item', 'cf7std' ),
    'update_item'           => __( 'Update Item', 'cf7std' ),
    'view_item'             => __( 'View Item', 'cf7std' ),
    'view_items'            => __( 'View Items', 'cf7std' ),
    'search_items'          => __( 'Search Item', 'cf7std' ),
    'not_found'             => __( 'Not found', 'cf7std' ),
    'not_found_in_trash'    => __( 'Not found in Trash', 'cf7std' ),
    'featured_image'        => __( 'Featured Image', 'cf7std' ),
    'set_featured_image'    => __( 'Set featured image', 'cf7std' ),
    'remove_featured_image' => __( 'Remove featured image', 'cf7std' ),
    'use_featured_image'    => __( 'Use as featured image', 'cf7std' ),
    'insert_into_item'      => __( 'Insert into item', 'cf7std' ),
    'uploaded_to_this_item' => __( 'Uploaded to this item', 'cf7std' ),
    'items_list'            => __( 'Items list', 'cf7std' ),
    'items_list_navigation' => __( 'Items list navigation', 'cf7std' ),
    'filter_items_list'     => __( 'Filter items list', 'cf7std' ),
);
$args = array(
    'label'                 => __( 'NWS Form submission', 'cf7std' ),
    'description'           => __( 'CF7 form submissions saved to DB', 'cf7std' ),
    'labels'                => $labels,
    'supports'              => array( 'title' ),
    'hierarchical'          => false,
    'public'                => false,
    'show_ui'               => false,
    'show_in_menu'          => false,
    'menu_position'         => 100,
    'menu_icon'             => 'dashicons-email',
    'show_in_admin_bar'     => false,
    'show_in_nav_menus'     => true,
    'can_export'            => true,
    'has_archive'           => false,
    'exclude_from_search'   => true,
    'publicly_queryable'    => false,
    'capability_type'       => 'post',
    'capabilities' => array(
        'create_posts' => 'do_not_allow',
    ),
    'map_meta_cap' => true
);
register_post_type( 'form_submission', $args );
